[CI] Update Workflow
The in-use github action hasn't been updated to work for 4.0+
So re-write the workflow

diff --git a/.github/workflows/gut.yml b/.github/workflows/gut.yml
--- a/.github/workflows/gut.yml
+++ b/.github/workflows/gut.yml
@@ -11,13 +11,39 @@ on:
 jobs:
   GUT:
     name: Run GUT tests
+    env:
+      G_VERSION: 4.2.2
+      GODOT: /usr/local/bin/godot
+      GUT_PARAMS: -gdir=res://tests/ -gjunit_xml_file=output.xml
+      GODOT_PARAMS: --headless
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-    - name: Docker Test
-      uses: ceceppa/godot-gut-ci@main
+    - name: Cache Godot Version
+      uses: actions/cache@v4
+      id: cache
       with:
-        # required
-        godot_version: "4.2"
-        gut_params: -gdir=res://tests/
+        path: /usr/local/bin/godot
+        key: ${{ runner.os }}-${{ hashFiles('/usr/local/bin/godot') }}
+    - name: Download Godot
+      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
+      run: |
+        wget https://github.com/godotengine/godot/releases/download/${G_VERSION}-stable/Godot_v${G_VERSION}-stable_linux.x86_64.zip
+        unzip Godot_v${G_VERSION}-stable_linux.x86_64.zip
+        echo "moving Godot_v${G_VERSION}-stable_linux.x86_64 to ${GODOT}"
+        mv Godot_v${G_VERSION}-stable_linux.x86_64 ${GODOT}
+    - uses: actions/checkout@v4
+    - name: Import Godot Project
+      run:
+        ${GODOT} ${GODOT_PARAMS} --import
+    - name: Run GUT tests
+      run:
+        ${GODOT} -s ${GODOT_PARAMS} --path $PWD addons/gut/gut_cmdln.gd -gexit ${GUT_PARAMS}
+    - name: Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() #always run even if previous step failed
+      with:
+        report_paths: output.xml
+    - uses: actions/upload-artifact@v4
+      with:
+        name: GUT-output
+        path: output.xml
